import { getCurrentLanguage } from '@/text';

const zh = {
    inboxTitle: 'AI协作会话',
    agents: 'Agents',
    agentsSubtitle: '创建和管理岗位、职责与工作边界',
    teams: 'AI团队',
    teamsSubtitle: '设置团队负责人、成员与协作方式',
    workspace: 'AI团队工作台',
    agentManagement: 'Agent管理',
    teamManagement: 'AI团队管理',
    currentWork: '当前工作',
    responsibilities: '主要职责',
    skills: '能力标签',
    belongsTo: '所属团队',
    members: '团队成员',
    leader: '团队负责人',
    instructions: '团队工作说明',
    currentGoal: '当前目标',
    progress: '当前进度',
    chat: '聊天',
    status: '状态',
    source: '任务来源',
    decisionRecorded: '决定已记录，团队将按照你的选择继续推进。',
    messagePlaceholder: '输入消息…',
    send: '发送',
    viewTeam: '查看团队',
    notFound: '未找到相关内容',
    completed: '已完成',
    active: '进行中',
    pending: '待处理',
    decision: '待你决定',
    workDetails: '任务详情',
};

const en: typeof zh = {
    inboxTitle: 'AI collaboration chats',
    agents: 'Agents',
    agentsSubtitle: 'Manage roles, responsibilities, and work boundaries',
    teams: 'AI teams',
    teamsSubtitle: 'Configure team leads, members, and collaboration',
    workspace: 'AI team workspace',
    agentManagement: 'Agent management',
    teamManagement: 'AI team management',
    currentWork: 'Current work',
    responsibilities: 'Responsibilities',
    skills: 'Skills',
    belongsTo: 'Teams',
    members: 'Team members',
    leader: 'Team lead',
    instructions: 'Team instructions',
    currentGoal: 'Current goal',
    progress: 'Progress',
    chat: 'Chat',
    status: 'Status',
    source: 'Source',
    decisionRecorded: 'Decision recorded. The team will continue with your selection.',
    messagePlaceholder: 'Message…',
    send: 'Send',
    viewTeam: 'View team',
    notFound: 'Content not found',
    completed: 'Completed',
    active: 'Active',
    pending: 'Pending',
    decision: 'Decision needed',
    workDetails: 'Work details',
};

export function getAiTeamCopy(): typeof zh {
    return getCurrentLanguage().startsWith('zh') ? zh : en;
}
